sources:
  - name: yellow_taxi_source
    schema: public
    tables:
      - name: yellow_taxi_trips
        identifier: yellow_taxi_trips_{{ env_var('DATA_PERIOD') }}
      - name: yellow_taxi_trips_stats
        identifier: yellow_taxi_trips_{{ env_var('DATA_PERIOD') }}_stats
