CREATE TABLE IF NOT EXISTS yellow_taxi_trips_{{get_data_period_ym(ds, -3)}} (
    VendorID               INTEGER,
    tpep_pickup_datetime   TIMESTAMP,
    tpep_dropoff_datetime  TIMESTAMP,
    passenger_count        BIGINT,
    trip_distance          FLOAT8,
    RatecodeID             BIGINT,
    store_and_fwd_flag     VARCHAR(5),
    PULocationID           INTEGER,
    DOLocationID           INTEGER,
    payment_code           BIGINT,
    fare_amount            DOUBLE PRECISION,
    extra                  DOUBLE PRECISION,
    mta_tax                DOUBLE PRECISION,
    tip_amount             DOUBLE PRECISION,
    tolls_amount           DOUBLE PRECISION,
    improvement_surcharge  DOUBLE PRECISION,
    total_amount           DOUBLE PRECISION,
    congestion_surcharge   DOUBLE PRECISION,
    Airport_fee            DOUBLE PRECISION,
    cbd_congestion_fee     DOUBLE PRECISION,
    IsWeekend              INTEGER NOT NULL,
    payment_type           VARCHAR(50),
    rate_type              VARCHAR(50),
    PULocation             VARCHAR(255),
    DOLocation             VARCHAR(255),
    Vendor                 VARCHAR(255),
    trip_id                VARCHAR(64) PRIMARY KEY
)
DISTSTYLE EVEN
SORTKEY (trip_id);