CREATE TABLE IF NOT EXISTS yellow_taxi_trips_{{get_data_period_ym(ds, -3)}} (
    VendorID               INTEGER,
    tpep_pickup_datetime   TIMESTAMP,
    tpep_dropoff_datetime  TIMESTAMP,
    passenger_count        BIGINT,
    trip_distance          FLOAT8,
    RatecodeID             BIGINT,
    store_and_fwd_flag     VARCHAR(5),
    PULocationID           INTEGER,
    DOLocationID           INTEGER,
    payment_code           BIGINT,
    fare_amount            DECIMAL(10, 2),
    extra                  DECIMAL(10, 2),
    mta_tax                DECIMAL(10, 2),
    tip_amount             DECIMAL(10, 2),
    tolls_amount           DECIMAL(10, 2),
    improvement_surcharge  DECIMAL(10, 2),
    total_amount           DECIMAL(10, 2),
    congestion_surcharge   DECIMAL(10, 2),
    Airport_fee            DECIMAL(10, 2),
    cbd_congestion_fee     DECIMAL(10, 2),
    IsWeekend              INTEGER NOT NULL,
    payment_type           VARCHAR(50),
    rate_type              VARCHAR(50),
    PULocation             VARCHAR(255),
    DOLocation             VARCHAR(255),
    Vendor                 VARCHAR(255),
    trip_id                VARCHAR(64) PRIMARY KEY
)
DISTSTYLE EVEN
SORTKEY (trip_id);